[package]
name = "port_sniffer"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.29.1", features = ["full"]}
bpaf = {version = "0.9.1", features = ["derive", "bright-color"]}
